### PR TITLE
Add German Translation File

### PR DESCRIPTION
**Pull request by phillipfickl**
Introduced a new formal German translation file to extend localization support. This file includes translations for all existing English strings. 

I hope you generally accept translations. Let me know if something is off. I've been using this in a German-speaking project for more than a year without any complaints so far.

### CODE REVIEW

**Comment by michael-milette** [comment]
Hi @phillipfickl ,

Thank you so much for your work. Could you please upload your German translation to AMOS at https://lang.moodle.org/

This is the official language pack manager for all plugins on Moodle.org and for Moodle itself.

Let me know if you need help.

Best regards,

Michael Milette

**Comment by phillipfickl** [comment]
Hi @michael-milette ,
done! I just submitted it. Thank you for your open source work!
Screenshot 2024-10-15 at 09 41 04

Best regards,
Phillip Fickl

**Comment by michael-milette** [comment]
Hi @phillipfickl ,

Thank you for sharing your screenshot. However, you uploaded it to German translations for Moodle Workplace instead of the Standard Moodle. Moodle Workplace is the commercial version of Moodle so your translations will not make it into the regular Moodle.

I suggest that you cancel your request for Moodle Workplace and please re-submit it for the Standard Moodle. That way, it will end up available for both versions of Moodle LMS.
image

Once you have submitted the language strings, it should be integrated and distributed to all Moodle sites using the German language pack around the world within a few days.

Let me know if you have any questions.

Best regards,

Michael

**Comment by phillipfickl** [comment]
Oh no! I see, yeah, looks like I did.
Well, switching to German (not for workplace) now, I can see that somebody else already submitted it 2 months ago:
Screenshot 2024-10-16 at 10 56 38
I guess this ticket can be closed.

Best,
Phillip

**Pull request closed without merging**
